# count_trees.R
# -------------
#
# Author:  Miles Erickson
# License: Freeware
#
# Description:
# Counts the number of trees adjacent to each sidewalk segment.
# 
# Background:
# This script has been prepared to complete the "Data Wrangling Project"
# assignment for the Springboard Foundations of Data Science Workshop.
# This project is intended to demonstrate competency in creating a tidy data
# set from real-world data sources.
#
# Additional details are located here:
# https://github.com/mileserickson/springboard_data-wrangling-project

# Required libraries
require(sp)     # SpatialLinesDataFrame, over()
require(rgdal)  # ReadOGR(), spTransform()
require(rgeos)  # gBuffer()
require(dplyr)  # %>%, group_by, summarise, left_join, etc

# Read the sidewalks GeoJSON file generated by output_geojson.R into a SpatialLinesDataFrame
sidewalks <- readOGR("data/sidewalks.json", "OGRGeoJSON")

# Add unique ID column
sidewalks$sidewalk_id <- 1:length(sidewalks)

# Extract sidewalk metadata
sidewalks.metadata <- sidewalks@data

# Rename OBJECTID column to sidewalk_objectid & designate as factor
sidewalks.metadata$sidewalk_objectid <- as.factor(sidewalks.metadata$OBJECTID)
sidewalks.metadata$OBJECTID <- NULL

# Load sidewalk SpatialLinesDataFrame cleaned up by AccessMap Seattle project team
sidewalks <- readOGR("data/sidewalk-grades-geoJSON-latest.json", "OGRGeoJSON")

# Align metadata rows to sidewalks SpatialLinesDataFrame rows
sidewalks.metadata <- data.frame(sidewalks) %>% left_join(sidewalks.metadata)

# Add important metadata columns to sidewalks SpatialLinesDataFrame 
sidewalks$description <- sidewalks.metadata$UNITDESC
sidewalks$condition <- sidewalks.metadata$CONDITION

# Load street trees shapefile
trees <- readOGR("data/Trees/StatePlane", "Trees")

# Reproject sidewalks to align with trees
sidewalks <- spTransform(sidewalks, CRS(proj4string(trees)))

# Buffer sidewalks by 20 feet
sidewalk_buffers <- gBuffer(sidewalks, width=20, byid=TRUE)

# Output sidewalk buffers to a shapefile for use in GIS software
writeOGR(sidewalk_buffers, 'data/sidewalk_buffers.json', driver='ESRI Shapefile')

# Identify the adjoining sidewalk for each individual tree
trees$sidewalk_id <- over(trees, sidewalk_buffers)$sidewalk_id
## BUG (minor): Each tree is attributed to one sidewalk at most,
##              despite that some sidewalk buffers may overlap slightly
##              near intersections. This could be resolved by performing
##              a spatial left join (e.g. in PostGIS) instead of using
##              sp::over() in R.

# Use dplyr to count the trees within the buffered area of each sidewalk
sidewalk_tree_counts <- data.frame(trees) %>%
  group_by(sidewalk_id) %>%
  summarise(tree_count = n())

# Add tree count as column in sidewalks data frame
sidewalks$tree_count <- left_join(sidewalks, sidewalk_tree_counts)$tree_count

# Change all NA values to 0
NAtoZero <- function(x) {ifelse(is.na(x), 0, x)}
sidewalks$tree_count <- as.numeric(lapply(sidewalks$tree_count, NAtoZero))

# Find lengths of sidewalks in feet
sidewalks$length <- SpatialLinesLengths(sidewalks)

# Normalize tree count by length
sidewalks$trees_per_ft <- sidewalks$tree_count / sidewalks$length

